name: LoESmithing
main: com.legendsofesper.wac.loesmithing.LoESmithing
version: 0.1
description: Controls commands, events, and functionality of LoE's unique smithing system.

commands:
    giveore:
        description: give special ore of your choice for plugin testing
        usage: /giveore <ore>